# =========================
# Server Configuration
# =========================
server:
  port: 8081

gateway:
  secret: hdsgaf8iouqkjgsdjkjasgd

spring:
  application:
    name: task-service

  # =========================
  # MySQL Database Configuration
  # =========================
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/taskservice
    username: root
    password: mkrk7500
    driver-class-name: com.mysql.cj.jdbc.Driver

  # =========================
  # JPA / Hibernate Configuration
  # =========================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # =========================
  # H2 Console
  # =========================
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-ui

# =========================
# Logging Configuration
# =========================
logging:
  level:
    root: INFO
    taskService: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# =========================
# Actuator & Prometheus Monitoring
# =========================
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true

# =========================
# Info Endpoint
# =========================
info:
  app:
    name: taskService
    description: Handles task management
