# =========================
# Server Configuration
# =========================
server.port=8082
spring.application.name=auth-service
logging.level.org.springframework.security=DEBUG
#logging.level.com.netflix.discovery=DEBUG
#logging.level.org.springframework.cloud.openfeign=DEBUG
#logging.level.feign=DEBUG
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# =========================
# Secret Key
# =========================
jwt.secret: ZA55GNm4rq3txxCKFFeFik7Sfr33nL55nXNAO7pTzTU=
jwt.expiration: 1800

# =========================
# Info Endpoint
# =========================
info.app.name=authService
info.app.description=Handles authentication